rootProject.name = 'Shoostr'
include 'http', 'core', 'test', 'pac4j', 'benchmarks', 'microbenchmarks'
project(':benchmarks').projectDir = file('.github/benchmarks')

include 'micrometer', 'opentelemetry'

include 'consumer-smoke'
project(':consumer-smoke').projectDir = file('examples/consumer-smoke')
